version: '3.9'

services:
  db:
    container_name: postgresql
    image: postgres:15-alpine
    volumes:
      - /var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_DB: "algosolved"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
      timeout: 120s
    networks:
      - algosolved-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: algosolved-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/algosolved
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_SERVER_PORT=8080
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: always
    networks:
      - algosolved-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    networks:
      - algosolved-network

networks:
  algosolved-network:
    driver: bridge
