version: '3.1'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    networks:
      - algosolved-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    networks:
      - algosolved-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=algosolved
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    expose:
      - "5433"
      - "5432"
    restart: always
    networks:
      - algosolved-network

networks:
  algosolved-network:
    driver: bridge