version: '3.9'

services:
  db:
    container_name: postgresql
    image: postgres:15-alpine
    volumes:
      - ${HOME}/algosolved/data/postgresql:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_DB: "algosolved"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: --encoding=UTF-8
      TZ: Asia/Seoul
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
      timeout: 120s
    networks:
      - algosolved-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: backend
    environment:
      - STAGE=development
      - TZ=Asia/Seoul
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      db:
        condition: service_healthy
      backend-job:
        condition: service_healthy
    ports:
      - 8080:8080
    restart: always
    volumes:
      - ./backend:/home/deploy/app/backend
    networks:
      - algosolved-network

  backend-job:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: backend-job
    environment:
      - STAGE=development
      - TZ=Asia/Seoul
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - ORG_JOBRUNR_BACKGROUND_JOB_SERVER_ENABLED=true
      - ORG_JOBRUNR_BACKGROUND_JOB_SERVER_PORT=8000
      - ORG_JOBRUNR_DASHBOARD_ENABLED=true
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/health/ping" ]
      interval: 5s
      timeout: 120s
      retries: 5
    networks:
      - algosolved-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./frontend:/usr/app/frontend

    depends_on:
      - backend
    networks:
      - algosolved-network

networks:
  algosolved-network:
    driver: bridge
